import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    agent: "src/agent/index.ts",
    "agent/request": "src/public/agent-request.ts",
    "agent/provider-types": "src/agent/provider-types.ts",
    "agent/types": "src/agent/types.ts",
    "agent/runtime": "src/agent/runtime.ts",
    "agent/session-store": "src/agent/session-store.ts",
    "agent/session-resume-utils": "src/agent/session-resume-utils.ts",
    "agent/pool": "src/agent/pool.ts",
    "agent/executor": "src/agent/executor.ts",
    "agent/tool-snapshot": "src/agent/tool-snapshot.ts",
    "agent/provider-mcp": "src/agent/provider-mcp.ts",
    "agent/thinking-level-patch": "src/agent/thinking-level-patch.ts",
    "agent/log-port": "src/agent/log-port.ts",
    "agent/service-status": "src/agent/service-status/index.ts",
    constants: "src/constants.ts",
    "streaming-sink": "src/public/streaming-sink.ts",
    job: "src/job/index.ts",
    carrier: "src/carrier/index.ts",
    "carrier/personas": "src/carrier/personas/index.ts",
    squadron: "src/squadron/index.ts",
    taskforce: "src/taskforce/index.ts",
    "carrier-jobs": "src/job/carrier-jobs/index.ts",
    store: "src/store/index.ts",
    bridge: "src/bridge/index.ts",
    "bridge/streaming": "src/bridge/streaming/index.ts",
    "bridge/panel": "src/bridge/panel/index.ts",
    "bridge/render": "src/bridge/render/index.ts",
    "bridge/carrier-ui": "src/bridge/carrier-ui/index.ts",
    admiral: "src/admiral/index.ts",
    "admiral/protocols": "src/admiral/protocols/index.ts",
    "admiral/standing-orders": "src/admiral/standing-orders/index.ts",
    "admiral/tool-prompt-manifest": "src/admiral/tool-prompt-manifest/index.ts",
    metaphor: "src/metaphor/index.ts",
    "metaphor/operation-name": "src/metaphor/operation-name/index.ts",
    "metaphor/directive-refinement": "src/metaphor/directive-refinement/index.ts",
    "grand-fleet": "src/grand-fleet/index.ts",
    "grand-fleet/ipc": "src/grand-fleet/ipc/protocol.ts",
    "grand-fleet/formation": "src/grand-fleet/formation/tmux.ts",
    "core-services": "src/core-services/index.ts",
    "core-services/settings": "src/core-services/settings/index.ts",
    "core-services/keybind": "src/core-services/keybind/index.ts",
    "core-services/log": "src/core-services/log/index.ts",
    "core-services/provider-guard": "src/core-services/provider-guard/index.ts",
    "experimental-wiki": "src/experimental-wiki/index.ts"
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "es2022"
});
