import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "agent/shared/types": "src/services/agent/shared/types.ts",
    "agent/shared/service-status": "src/services/agent/shared/service-status/index.ts",
    "agent/provider/provider-types": "src/services/agent/provider/provider-types.ts",
    "agent/provider/provider-client": "src/services/agent/provider/provider-client.ts",
    "agent/provider/provider-mcp": "src/services/agent/provider/provider-mcp.ts",
    "agent/provider/thinking-level-patch": "src/services/agent/provider/thinking-level-patch.ts",
    "agent/provider/tool-snapshot": "src/services/agent/provider/tool-snapshot.ts",
    "agent/dispatcher/runtime": "src/services/agent/dispatcher/runtime.ts",
    "agent/dispatcher/session-store": "src/services/agent/dispatcher/session-store.ts",
    "agent/dispatcher/session-resume-utils": "src/services/agent/dispatcher/session-resume-utils.ts",
    "agent/dispatcher/pool": "src/services/agent/dispatcher/pool.ts",
    "agent/dispatcher/executor": "src/services/agent/dispatcher/executor.ts",
    constants: "src/constants.ts",
    job: "src/services/job/index.ts",
    "admiral/carrier": "src/admiral/carrier/index.ts",
    "admiral/carrier/personas": "src/admiral/carrier/personas/index.ts",
    "admiral/squadron": "src/admiral/squadron/index.ts",
    "admiral/taskforce": "src/admiral/taskforce/index.ts",
    "carrier-jobs": "src/admiral/carrier-jobs/index.ts",
    "admiral/store": "src/admiral/store/index.ts",
    admiralty: "src/admiralty/index.ts",
    "admiral/bridge/run-stream": "src/admiral/bridge/run-stream/index.ts",
    "admiral/bridge/carrier-panel": "src/admiral/bridge/carrier-panel/index.ts",
    "admiral/bridge/carrier-control": "src/admiral/bridge/carrier-control/index.ts",
    admiral: "src/admiral/index.ts",
    "admiral/protocols/standing-orders": "src/admiral/protocols/standing-orders/index.ts",
    "services/tool-registry": "src/services/tool-registry/index.ts",
    metaphor: "src/metaphor/index.ts",
    "metaphor/operation-name": "src/metaphor/operation-name/index.ts",
    "metaphor/directive-refinement": "src/metaphor/directive-refinement/index.ts",
    "services/settings": "src/services/settings/index.ts",
    "services/log": "src/services/log/index.ts"
  },
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "es2022"
});
