export type { CarrierConfig } from "@sbluemin/fleet-core/admiral/carrier";

export {
  disableSortieCarrier,
  disableSquadronCarrier,
  enableSortieCarrier,
  enableSquadronCarrier,
  getActiveSquadronIds,
  getActiveTaskForceIds,
  getAllCliTypes,
  getRegisteredCarrierConfig,
  getRegisteredOrder,
  getSortieDisabledIds,
  getSortieEnabledIds,
  getSquadronEnabledIds,
  getTaskForceConfiguredIds,
  isSortieCarrierEnabled,
  isSquadronCarrierEnabled,
  notifyStatusUpdate,
  onStatusUpdate,
  registerCarrier,
  reorderRegisteredByCliType,
  resolveCarrierBgColor,
  resolveCarrierCliDisplayName,
  resolveCarrierColor,
  resolveCarrierDisplayName,
  resolveCarrierRgb,
  setPendingCliTypeOverrides,
  setSortieDisabledCarriers,
  setSquadronEnabledCarriers,
  setTaskForceConfiguredCarriers,
  updateCarrierCliType,
} from "../../tool-registry.js";
